-- Criação da tabela Membro (Member)
CREATE TABLE member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cargo VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);

-- Criação da tabela Projeto (Project)
CREATE TABLE project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(255),
    status VARCHAR(255) NOT NULL
);

-- Tabela de Junção (Many-to-Many)
-- Quem está em qual projeto?
CREATE TABLE member_project (
    member_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,

    -- Chave Primária Composta (evita duplicatas do mesmo par)
    PRIMARY KEY (member_id, project_id),

    -- Chaves Estrangeiras (Garante integridade)
    CONSTRAINT fk_member FOREIGN KEY (member_id) REFERENCES member(id),
    CONSTRAINT fk_project FOREIGN KEY (project_id) REFERENCES project(id)
);